### ISSUE TITLE
It would be great to use the existing boot2docker ssh key

### ISSUE THREAD

**Issue by andrechrist** [jkingyens/b2d-sync#4]
Currently I need to copy my ssh key into boot2docker before I start bdsync (via ssh-copy-id). I dont't think this is really needed as we could use the ssh key at ~/.ssh/id_boot2docker for the connection.

What do you think? If you are ok with the approach, I could work on this ...

**Comment by jkingyens** [comment]
Sure, that sounds good :+1:
